version: '2'
services:
  pds-ui:
    restart: always
    container_name: pds-ui
    image: pds-ui-image
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 800m
    networks:
      - traefik
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pds-ui.rule=Host(`podstrochnik.ru`)"
      - "traefik.http.routers.pds-ui.entrypoints=websecure"
      - "traefik.http.routers.pds-ui.tls.certresolver=myresolver"
      - "traefik.http.routers.pds-ui.tls=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.pds-ui.middlewares=redirect-to-https"
      - "traefik.http.services.pds-ui.loadbalancer.server.port=3003"

networks:
  default:
    external: false
  traefik:
    external: true
