version: "3.9"

services:
  pds-ui:
    restart: always
    container_name: pds-ui-v2

    image: pds-ui-image-v2
    build:
      context: .
      dockerfile: Dockerfile

    mem_limit: 800m

    networks:
      - traefik

    labels:
      - "traefik.enable=true"

      # Router
      - "traefik.http.routers.podstrochnik.rule=Host(`podstrochnik.alialiev.com`)"
      - "traefik.http.routers.podstrochnik.entrypoints=websecure"
      - "traefik.http.routers.podstrochnik.tls=true"
      - "traefik.http.routers.podstrochnik.tls.certresolver=myresolver"

      # Service port inside container
      - "traefik.http.services.podstrochnik.loadbalancer.server.port=3003"

      # Network
      - "traefik.docker.network=traefik"

networks:
  traefik:
    external: true
